using System;
using Leopotam.EcsLite;
using td.features.eventBus;
using td.utils;
using td.utils.ecs;

// This is AutoGenerated file!
namespace td.features.state
{
    [Serializable]
    public abstract class StateBase : IState
    {
        [Inject] protected EventBus eventBus = default;
        [InjectSystems] protected IEcsSystems systems = default;
        
        protected bool eventsSuspended;

        protected float maxLives;
        public float MaxLives
        {
            get => maxLives;
            set
            {
                if (FloatUtils.IsEquals(maxLives, value)) return;
                maxLives = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().maxLives = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { maxLives = value });
            }
        }

        protected float lives;
        public float Lives
        {
            get => lives;
            set
            {
                if (FloatUtils.IsEquals(lives, value)) return;
                lives = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().lives = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { lives = value });
            }
        }

        protected uint levelNumber;
        public uint LevelNumber
        {
            get => levelNumber;
            set
            {
                if (levelNumber == value) return;
                levelNumber = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().levelNumber = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { levelNumber = value });
            }
        }

        protected int money;
        public int Money
        {
            get => money;
            set
            {
                if (money == value) return;
                money = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().money = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { money = value });
            }
        }

        protected float nextWaveCountdown;
        public float NextWaveCountdown
        {
            get => nextWaveCountdown;
            set
            {
                if (FloatUtils.IsEquals(nextWaveCountdown, value)) return;
                nextWaveCountdown = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().nextWaveCountdown = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { nextWaveCountdown = value });
            }
        }

        protected int waveNumber;
        public int WaveNumber
        {
            get => waveNumber;
            set
            {
                if (waveNumber == value) return;
                waveNumber = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().waveNumber = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { waveNumber = value, waveCount = waveCount});
            }
        }

        protected int waveCount;
        public int WaveCount
        {
            get => waveCount;
            set
            {
                if (waveCount == value) return;
                waveCount = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().waveCount = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { waveNumber = waveNumber, waveCount = value });
            }
        }

        protected int enemiesCount;
        public int EnemiesCount
        {
            get => enemiesCount;
            set
            {
                if (enemiesCount == value) return;
                enemiesCount = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().enemiesCount = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { enemiesCount = value });
            }
        }
        
        protected float gameSpeed;
        public float GameSpeed
        {
            get => gameSpeed;
            set
            {
                if (FloatUtils.IsEquals(gameSpeed,value)) return;
                gameSpeed = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().gameSpeed = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { gameSpeed = value });
            }
        }

        protected bool isBuildingProcess;
        public bool IsBuildingProcess
        {
            get => isBuildingProcess;
            set
            {
                if (isBuildingProcess == value) return;
                isBuildingProcess = value;
                if (!eventsSuspended) systems.Outer<StateChangedOuterEvent>().isBuildingProcess = true;
                if (!eventsSuspended) eventBus.Send(new StateChangedEvent { isBuildingProcess = value });
            }
        }

        public void SuspendEvents() => eventsSuspended = true;
        public void ResumeEvents()
        {
            eventsSuspended = false;
            eventBus.Send(StateChangedEvent.FromState(this));
        }

        public void Refresh() {
            eventsSuspended = false;
            systems.Outer<StateChangedOuterEvent>() = StateChangedOuterEvent.AllTrue();
            eventBus.Send(StateChangedEvent.FromState(this));
        }

        public void Clear() {
            maxLives = default;
            lives = default;
            levelNumber = default;
            money = default;
            nextWaveCountdown = default;
            waveNumber = default;
            waveCount = default;
            enemiesCount = default;
            gameSpeed = 1f;
            isBuildingProcess = default;
        }
    }
}