// This is AutoGenerated file!
namespace td.features.state
{
    public struct StateChangedEvent
    {
        public bool? maxLives;
        public bool? lives;
        public bool? levelNumber;
        public bool? money;
        public bool? nextWaveCountdown;
        public bool? waveNumber;
        public bool? waveCount;
        public bool? enemiesCount;
        public bool? isBuildingProcess;
    }
}