// This is AutoGenerated file! TODO

using td.features.eventBus;

namespace td.features.state
{
    public struct StateChangedEvent : IEvent
    {
        public float? maxLives;
        public float? lives;
        public uint? levelNumber;
        public int? money;
        public float? nextWaveCountdown;
        public int? waveNumber;
        public int? waveCount;
        public int? enemiesCount;
        public bool? isBuildingProcess;
        public float? gameSpeed;

        public static StateChangedEvent FromState(IState state) =>
            new()
            {
                waveCount = state.WaveCount,
                waveNumber = state.WaveNumber,
                isBuildingProcess = state.IsBuildingProcess,
                nextWaveCountdown = state.NextWaveCountdown,
                lives = state.Lives,
                money = state.Money,
                enemiesCount = state.EnemiesCount,
                levelNumber = state.LevelNumber,
                gameSpeed = state.GameSpeed,
                maxLives = state.MaxLives,
            };
    }
}
