// This is AutoGenerated file!
namespace td.features.state
{
    public struct StateChangedOuterEvent
    {
        public bool? maxLives;
        public bool? lives;
        public bool? levelNumber;
        public bool? money;
        public bool? nextWaveCountdown;
        public bool? waveNumber;
        public bool? waveCount;
        public bool? enemiesCount;
        public bool? isBuildingProcess;
        public bool? gameSpeed;
        
        public static StateChangedOuterEvent AllTrue() =>
            new()
            {
                waveCount = true,
                waveNumber = true,
                isBuildingProcess = true,
                nextWaveCountdown = true,
                lives = true,
                money = true,
                enemiesCount = true,
                levelNumber = true,
                gameSpeed = true,
                maxLives = true,
            };
    }
}